### PR TITLE
Modified web.xml rest url route

### PR DESCRIPTION
**Pull request by rdyapa**
mode route changes in web.xml file

### CODE REVIEW

**Review by Adithyasirikonda — COMMENTED** [review]
good modification.

**Comment by nuthanpradeep** [comment]
modification is done as per user need

**Review by Shruthikonakati — COMMENTED** [review]
ok

**Review by Suman1987 — COMMENTED** [review]
good

**Review by gopi6666 — APPROVED** [review]
gopi reviewed the changes

**Pull request merged**
